### ISSUE TITLE
authentication fails when provided REPLICATE_API_TOKEN on versions 0.14.0 and greater

### ISSUE THREAD

**Issue by Mohsin-Ul-Islam** [replicate/replicate-python#169] opened 2023-10-08 17:21 UTC
on versions 0.14.0 and greater, the client gives `you have not passed an authentication token`.

**Comment by extrange** [comment] 2023-10-09 06:17
Having the same issue with `0.15.3`.

I think it's due to the `Client` reading the `REPLICATE_API_TOKEN` on library import:

https://github.com/replicate/replicate-python/blob/30e4be55f96768b9d607cc8ddddb61f5aabcb3b3/replicate/client.py#L29C18-L40

I fixed this by importing the library after the environment variables are available, e.g.

```python
# This needs to be before the llm library imports, otherwise they won't see the loaded environment variables
load_dotenv()

import replicate
```

**Comment by thijssdaniels** [comment] 2023-10-09 10:18
I'm experiencing the same problem too. Using the default Colab available for fine-tuning a model on my own pictures

**Comment by mattt** [comment] 2023-10-09 11:03
@Mohsin-Ul-Islam Thanks for reporting this. I apologize for any inconvenience there.

@extrange is exactly right that this new behavior is caused by a change in how the default client is initialized at the time of import.

@thijssdaniels The [Colab notebook linked from the README](https://colab.research.google.com/drive/1K91q4p-OhL96FHBAVLsv9FlwFdu6Pn3c) demonstrates how to get started with Replicate.

Some users are reporting problems with this change, so I'm looking at different ways to communicate or mitigate this problem.

**Comment by Lazymindz** [comment] 2023-10-09 11:39
@thijssdaniels i modified the notebook based on @extrange's suggestion and it now works.

You could refer to:
https://colab.research.google.com/drive/1D1MvippwX-qDm6MdUmuTJlnmCX3yIvUo?usp=sharing

changes:
Comment out the import of replicate at the start and import only after the env. variables are set.

@mattt just fyi. the README colab just state this either. Someone running the readme colab would still face this issue.

**Comment by mattt** [comment] 2023-10-09 11:44
I just merged #170 with a change that should restore the previous behavior. Please upgrade to [0.15.4](https://github.com/replicate/replicate-python/releases/tag/0.15.4) and let me know if you're still seeing this issue. Thanks!

**Closed by mattt** 2023-10-09 11:44 UTC

**Comment by Mhs467** [comment] 2024-08-22 09:43
from dotenv import load_dotenv
import os
load_dotenv()

# Load environment variables from .env file
print("Loading environment variables...")

import replicate
api_token = os.getenv("REPLICATE_API_TOKEN")
print(f"API Token Loaded: {api_token}")

# Initialize the Replicate client with your API token
print("Initializing Replicate client...")
replicate_client = replicate.Client(api_token=api_token)

def predict_image(filename):
    try:
        print(f"Predicting image for file: {filename}")

        # Retrieve the model
        print("Retrieving the model...")
        model = replicate_client.models.get("tencentarc/gfpgan")
        print(f"Model retrieved: {model}")

        # List all available versions
        print("Listing all available versions...")
        for version in model.versions.list():
            print(f"Version ID: {version.id}, Created At: {version.created_at}")

        # Retrieve the latest version (or specify a particular one)
        print("Retrieving the latest version of the model...")
        latest_version = model.versions.get("ae80bbe1adce7d616b8a96ba88a91d3556838d4f2f4da76327638b8e95ea4694")  # You might replace "latest" with an actual version ID if needed
        print(f"Latest version retrieved: {latest_version}")

        # Prepare the inputs for the model prediction
        print("Preparing inputs for the model prediction...")
        inputs = {
            "img": open(filename, "rb"),  # Opening the image file in binary mode
            "scale": 2  # Rescaling factor
        }
        print(f"Inputs prepared: {inputs}")

        # Run the model prediction with the latest version
        print("Running the model prediction...")
        output = replicate.run("tencentarc/gfpgan:0fbacf7afc6c144e5be9767cff80f25aff23e52b0708f17e20f9879b2f21516c", input=inputs)
        print(f"Prediction output: {output}")

        return output  # Assuming the output is the URL of the restored image

    except Exception as e:
        print(f"An error occurred: {str(e)}")
        raise

# Example usage
# output_url = predict_image("path_to_your_image.jpg")
# print(f"Restored image URL: {output_url}")
I am using this code but I still get the same error. Can anyone help please? I have tried everything told above

**Comment by mattt** [comment] 2024-08-22 10:23
@Mhs467 In your code sample, the line starting `output = replicate.run("tencentarc/gfpgan...` uses the default Replicate client instance instead of the `replicate_client` constructed earlier. I don't see why the default client wouldn't pick up the API token from the environment automatically, but that at least accounts for the unexpected error.

**Comment by Mhs467** [comment] 2024-08-22 10:36
Thank you for the speedy response matt. Means a lot. Let me implement your
suggestion

**Comment by Mhs467** [comment] 2024-08-22 10:46
import os
from dotenv import load_dotenv
load_dotenv()
import replicate

# Load environment variables from .env file


# Initialize the Replicate client
api_token = os.getenv("REPLICATE_API_TOKEN")
replicate_client = replicate.Client(api_token=api_token)

def predict_image(filename):
    try:
        print(f"Predicting image for file: {filename}")

        # Retrieve the model
        model = replicate_client.models.get("tencentarc/gfpgan")
        print(f"Model retrieved: {model}")

        # Retrieve the latest version
        latest_version = model.versions.get(
"0fbacf7afc6c144e5be9767cff80f25aff23e52b0708f17e20f9879b2f21516c")
        print(f"Latest version retrieved: {latest_version}")

        # Prepare the inputs for the model prediction
        inputs = {
            "img": open(filename, "rb"),
            "scale": 2
        }

        # Run the model prediction using the replicate_client instance
        output = replicate_client.run(
"tencentarc/gfpgan:0fbacf7afc6c144e5be9767cff80f25aff23e52b0708f17e20f9879b2f21516c",
input=inputs)
        print(f"Prediction output: {output}")

        return output

    except replicate.exceptions.ReplicateError as e:
        print(f"ReplicateError occurred: {e}")
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        raise

title: Invalid version or not permitted
status: 422
detail: The specified version does not exist (or perhaps you don't have
permission to use it?) Still the same error

**Comment by mattt** [comment] 2024-08-22 11:15
@Mhs467 Hmm, are you using the latest version of the `replicate` package? What do you see in `pip list`?

**Comment by Mhs467** [comment] 2024-08-22 11:22
replicate                         0.31.0

This one.
When  this didnt work I tried downgrading 0.15.4 but that didn't work to so
I reverted back and tried this again. Same error. Let me ask a question and
that might be a little silly too: Is payment method required before we can
use the API or can we use it for free for some limited amount of requests.

**Comment by nedwards-loop** [comment] 2024-08-24 11:01
I am having a similar issue with the dreambooth example....

`from dotenv import load_dotenv
import os
load_dotenv()
import replicate

input = {
    "class_prompt": "a photo of a man",
    "instance_data": "https://replicate.delivery/pbxt/HoUeWsrtTTCJEpKGdLKqIYTfo8nbUTSNs565MkGxEstjfwKt/data.zip",
    "instance_prompt": "a photo of bfirsh"
}

output = replicate.run(
    "replicate/dreambooth:a8ba568da0313951a6b311b43b1ea3bf9f2ef7b9fd97ed94cebd7ffd2da66654",
    input=input
)
print(output)
#=> "https://replicate.delivery/pbxt/4lrw9387HOaKKR7kHv5YX4N5...`

This returns the error:

`ReplicateError: ReplicateError Details:
title: Invalid version or not permitted
status: 422
detail: The specified version does not exist (or perhaps you don't have permission to use it?)`

I don't have a credit card on my account, would that cause the issue?

**Comment by Mhs467** [comment] 2024-08-24 15:20
Try adding a payment method first.

**Comment by nedwards-loop** [comment] 2024-08-25 10:23
That worked! Thanks
