### ISSUE TITLE
replicate.exceptions.ReplicateError: HTTP error: (413, 'Request Entity Too Large')

### ISSUE THREAD

**Issue by raspipy** [replicate/replicate-python#157] opened 2023-10-01 20:12 UTC
So i'm using the replicate whisper API (openai/whisper:e39e354773466b955265e969568deb7da217804d8e771ea8c9cd0cef6591f8bc)
It's been wroking fantastic on smaller files but any file bigger than 80mb gives me the error
`replicate.exceptions.ReplicateError: HTTP error: (413, 'Request Entity Too Large')`

but when i'm using the website it works fine

Anyone know the problem?

This is my code
` output = replicate.Client().run("openai/whisper:e39e354773466b955265e969568deb7da217804d8e771ea8c9cd0cef6591f8bc",
                                                    input={"audio": open(File_Path.get(), "rb")})
        F.pack_forget()`
(File_Path is getting obtained from a Tkinter input field)

**Comment by natelalor** [comment] 2023-10-02 17:20
Hey there,
This has been mentioned [here](https://github.com/replicate/replicate-python/issues/68) and [here](https://github.com/replicate/replicate-python/issues/135). From my understanding, as I shoot to solve the same problem: the workaround is to provide it a URL since it is using HTTP, GET method has a specific size limit. 
Hopefully these links can help you!

**Comment by mattt** [comment] 2023-10-03 13:55
Thanks for responding, @natelalor.

Closing as a duplicate of https://github.com/replicate/replicate-python/issues/68

**Closed by mattt** 2023-10-03 13:55 UTC
