### ISSUE TITLE
dose train interface  officially not surported?

### ISSUE THREAD

**Issue by sinopec** [replicate/replicate-python#332] opened 2024-08-06 03:42 UTC
I found the train button in the webui all disappeared and some models use the prediction api
to train .

**Is it true that there will no longer be separate training interfaces, and instead, the training functionality will be implemented using inference interfaces?**

**Comment by mattt** [comment] 2024-08-06 06:00
Closing as duplicate of https://github.com/replicate/cog/issues/1853

**Closed by mattt** 2024-08-06 06:00 UTC
